class_name LevelGenerator
extends Node

signal generation_done

@export var corr_length := 256
@export var room_size := 256
@export var num_rooms := 14
@export var room_scenes: Array[PackedScene]
@export var vert_corr_scenes: Array[PackedScene]
@export var hori_corr_scenes: Array[PackedScene]

var rng = RandomNumberGenerator.new()

var office: Dictionary = {}
var rooms: Dictionary = {}

var directions = [
	Vector2i.UP,
	Vector2i.DOWN,
	Vector2i.LEFT,
	Vector2i.RIGHT
]

func rng_shuffle(arr: Array):
	'''
	Shuffles with RNG so can be deterministic by seed
	'''
	for i in range(0, arr.size()):
		var j = rng.randi_range(0, i)
		var tmp = arr[i]
		arr[i] = arr[j]
		arr[j] = tmp


func generate_layout():
	'''
	Generate the layout of the office
	'''
	office.clear()
	rooms.clear()
	
	var frontier: Array[Vector2i] = [Vector2i.ZERO]
	office[Vector2i.ZERO] = true
	
	while office.size() < num_rooms:
		# Choose random room from frontier to branch out from
		var curr: Vector2i = frontier[rng.randi_range(0, frontier.size() - 1)]
		
		# randomize the directions
		rng_shuffle(directions)
		
		var placeable := false
		
		for dir in directions:
			var next = curr + dir
			
			# if room in direction then continue to next direction
			if office.has(next):
				continue
				
			office[next] = true
			frontier.append(next)
			
			placeable = true
			break
		
		# if all directions blocked
		if not placeable:
			frontier.erase(curr)


func get_doors(pos):
	return {
		Room.Direction.NORTH: office.has(pos + Vector2i.UP),
		Room.Direction.SOUTH: office.has(pos + Vector2i.DOWN),
		Room.Direction.EAST: office.has(pos + Vector2i.RIGHT),
		Room.Direction.WEST: office.has(pos + Vector2i.LEFT)
	}
	
func create_corridor(from, to):
	var scene
	
	if to.x > from.x:
		#RIGHT
		scene = hori_corr_scenes[rng.randi_range(0, hori_corr_scenes.size() - 1)].instantiate()
		scene.position = Vector2(
			from.x * (corr_length + room_size) + corr_length,
			from.y * (corr_length + room_size)
		)
		
	if to.y > from.y:
		#UP
		scene = vert_corr_scenes[rng.randi_range(0, hori_corr_scenes.size() - 1)].instantiate()
		scene.position = Vector2(
			from.x * (corr_length + room_size),
			from.y * (corr_length + room_size) + corr_length
		)

	add_child(scene)

func generate_corridors():
	for pos in office.keys():
		if office.has(pos + Vector2i.RIGHT):
			create_corridor(pos, pos + Vector2i.RIGHT)
		if office.has(pos + Vector2i.UP):
			create_corridor(pos, pos + Vector2i.UP)


func choose_room(door):
	'''
	Chooses a room from rooms with the specified doors
	'''
	var valid: Array[PackedScene] = []
	
	# Get rooms that fit the specifications
	for scene in room_scenes:
		var folder := scene.resource_path.get_base_dir().get_file()
		var room_doors = Room.get_door_from_string(folder)

		var fits := true
		for dir in Room.Direction.values():
			if room_doors[dir] != door[dir]:
				fits = false
				break
		if fits:
			valid.append(scene)
		
	if valid.is_empty():
		return null
	
	return valid[rng.randi_range(0, valid.size() - 1)]


func choose_rooms():
	'''
	Chooses all the rooms to fit the layout generated by generate_layout
	'''
	for pos in office.keys():
		var doors = get_doors(pos)
		var room = choose_room(doors)
		
		if room == null:
			print("No valid room found")
			continue
		
		var iroom: Room = room.instantiate()
		
		iroom.position = Vector2(
			pos.x * (iroom.room_size+corr_length),
			pos.y * (iroom.room_size+corr_length)
		)
		
		add_child(iroom)
		
		rooms[pos] = iroom


func generate(seed: int = -99999):
	'''
	Generates seed if none specified
	'''
	if seed == -99999:
		rng.randomize()
		seed = rng.seed
	else:
		rng.seed = seed
		
	print("Using seed: ", seed)
	
	generate_layout()
	choose_rooms()
	generate_corridors()
	
	generation_done.emit()
