class_name LevelGenerator
extends Node

signal generation_done

@export var num_rooms := 6
@export var room_scenes: Array[PackedScene]

var rng = RandomNumberGenerator.new()

var office: Dictionary = {}
var rooms: Dictionary = {}

var directions = [
	Vector2i.UP,
	Vector2i.DOWN,
	Vector2i.LEFT,
	Vector2i.RIGHT
]

func rng_shuffle(arr: Array):
	'''
	Shuffles with RNG so can be deterministic by seed
	'''
	for i in range(0, arr.size()):
		var j = rng.randi_range(0, i)
		var tmp = arr[i]
		arr[i] = arr[j]
		arr[j] = tmp


func generate_layout():
	'''
	Generate the layout of the office
	'''
	office.clear()
	rooms.clear()
	
	var frontier: Array[Vector2i] = [Vector2i.ZERO]
	office[Vector2i.ZERO] = true
	
	while office.size() < num_rooms:
		# Choose random room from frontier to branch out from
		var curr: Vector2i = frontier[rng.randi_range(0, frontier.size() - 1)]
		
		# randomize the directions
		rng_shuffle(directions)
		
		var placeable := false
		
		for dir in directions:
			var next = curr + dir
			
			# if room in direction then continue to next direction
			if office.has(next):
				continue
				
			office[next] = true
			frontier.append(next)
			
			placeable = true
			break
		
		# if all directions blocked
		if not placeable:
			frontier.erase(curr)


func get_doors(pos):
	return {
		Room.Direction.NORTH: office.has(pos + Vector2i.UP),
		Room.Direction.SOUTH: office.has(pos + Vector2i.DOWN),
		Room.Direction.EAST: office.has(pos + Vector2i.RIGHT),
		Room.Direction.WEST: office.has(pos + Vector2i.LEFT)
	}


func choose_room(door):
	'''
	Chooses a room from rooms with the specified doors
	'''
	var valid: Array[PackedScene] = []
	
	# Get rooms that fit the specifications
	for scene in room_scenes:
		var room: Room = scene.instantiate()
		var fits := true
		for dir in Room.Direction.values():
			if room.has_door[dir] != door[dir]:
				fits = false
				break
		if fits:
			valid.append(scene)
		
	if valid.is_empty():
		return null
	
	return valid[rng.randi_range(0, valid.size() - 1)]


func choose_rooms():
	'''
	Chooses all the rooms to fit the layout generated by generate_layout
	'''
	for pos in office.keys():
		var doors = get_doors(pos)
		var room = choose_room(doors)
		
		if room == null:
			print("No valid room found")
		
		var iroom: Room = room.instantiate 
		iroom.position = Vector2(
			pos.x * room.room_size,
			pos.y * room.room_size
		)
		
		add_child(room)
		
		rooms[pos] = room


func generate_seed(seed: int = -99999):
	'''
	Generates seed if none specified
	'''
	if seed == -99999:
		rng.randomize()
		seed = rng.seed
	else:
		rng.seed = seed
		
	print("Using seed: ", seed)
	
	generate_layout()
	choose_rooms()
	
	generation_done.emit()
	
