class_name LevelGenerator
extends Node

signal generation_done

@export var corr_length := 256
@export var room_size := 256
@export var num_rooms := 28
@export var room_scenes: Array[PackedScene]
@export var vert_corr_scenes: Array[PackedScene]
@export var hori_corr_scenes: Array[PackedScene]

var rng = RandomNumberGenerator.new()

var office: Dictionary[Vector2i, bool] = {}
var room_by_coords: Dictionary[Vector2i, Room] = {}

var directions = [
	Vector2i.UP,
	Vector2i.DOWN,
	Vector2i.LEFT,
	Vector2i.RIGHT
]

func get_distance() -> Dictionary:
	var distances := {}
	var queue: Array[Vector2i] = [Vector2i.ZERO]
	distances[Vector2i.ZERO] = 0
	
	# BFS
	while !queue.is_empty():
		var curr = queue.pop_front()
		for direction in directions:
			var next = curr + direction
			if !office.has(next):
				continue
				
			if distances.has(next):
				continue
				
			distances[next] = distances[curr] + 1
			queue.push_back(next)
	
	return distances

func choose_boss_room():
	var distance = get_distance()
	var candidates = []
	for pos in distance.keys():
		if distance[pos] >= 2:
			candidates.append(pos)
	
	return candidates[rng.randi_range(0, candidates.size() - 1)]

func rng_shuffle(arr: Array):
	'''
	Shuffles with RNG so can be deterministic by seed
	'''
	for i in range(0, arr.size()):
		var j = rng.randi_range(0, i)
		var tmp = arr[i]
		arr[i] = arr[j]
		arr[j] = tmp


func generate_layout():
	office.clear()
	
	# The frontier now stores pairs: [Vector2i position, int doors_already_assigned]
	# Start at (0,0) with 0 doors assigned
	var frontier: Array[Vector2i] = [Vector2i.ZERO]
	office[Vector2i.ZERO] = true
	
	# Track total unfulfilled doors across the entire layout
	var active_branches := 0
	
	while office.size() < num_rooms:
		if frontier.is_empty():
			break # Safety check if we get boxed in early
			
		var curr = frontier[rng.randi_range(0, frontier.size() - 1)]
		rng_shuffle(directions)
		
		var placed := false
		
		for dir in directions:
			var next = curr + dir
			
			if office.has(next):
				continue
			
			office[next] = true
			frontier.append(next)
			placed = true
			break
			
		if not placed:
			frontier.erase(curr)

func get_doors(pos) -> Dictionary[Room.Direction, bool]:
	return {
		Room.Direction.NORTH: office.has(pos + Vector2i.UP),
		Room.Direction.SOUTH: office.has(pos + Vector2i.DOWN),
		Room.Direction.EAST: office.has(pos + Vector2i.RIGHT),
		Room.Direction.WEST: office.has(pos + Vector2i.LEFT)
	}
	
func create_corridor(from, to):
	var scene
	var step_distance = room_size + corr_length
	
	if to.x > from.x:
		#RIGHT
		scene = hori_corr_scenes[rng.randi_range(0, hori_corr_scenes.size() - 1)].instantiate()
		scene.position = Vector2(
			from.x * step_distance + (room_size / 2.0) + (corr_length / 2.0),
			from.y * step_distance
		)
		
	if to.y > from.y:
		#UP
		scene = vert_corr_scenes[rng.randi_range(0, vert_corr_scenes.size() - 1)].instantiate()
		scene.position = Vector2(
			from.x * step_distance,
			from.y * step_distance + (room_size / 2.0) + (corr_length / 2.0)
		)

	add_child(scene)

func generate_corridors():
	for pos in office.keys():
		if office.has(pos + Vector2i.RIGHT):
			create_corridor(pos, pos + Vector2i.RIGHT)
		if office.has(pos + Vector2i.DOWN):
			create_corridor(pos, pos + Vector2i.DOWN)


func choose_room(door):
	'''
	Chooses a room from rooms with the specified doors
	'''
	var valid: Array[PackedScene] = []
	
	# Get rooms that fit the specifications
	for scene in room_scenes:
		var folder := scene.resource_path.get_base_dir().get_file()
		var room_doors = Room.get_door_from_string(folder)

		var fits := true
		for dir in Room.Direction.values():
			if room_doors[dir] != door[dir]:
				fits = false
				break
		if fits:
			valid.append(scene)
		
	if valid.is_empty():
		return null
	
	return valid[rng.randi_range(0, valid.size() - 1)]


func choose_rooms():
	'''
	Chooses all the rooms to fit the layout generated by generate_layout
	'''
	for pos in office.keys():
		var doors = get_doors(pos)
		var room = choose_room(doors)
		
		if room == null:
			print("No valid room found")
			continue
		
		var iroom: Room = room.instantiate()
		
		var step_distance = room_size + corr_length
		
		iroom.position = Vector2(
			pos.x * step_distance,
			pos.y * step_distance
		)
		
		room_by_coords[pos] = iroom
		
		add_child(iroom)
	
	for pos in room_by_coords.keys():
		for dir in Room.Direction:
			var vector_dir: Vector2i
			match Room.Direction[dir]:
				Room.Direction.NORTH:
					vector_dir = Vector2i.UP
				Room.Direction.SOUTH:
					vector_dir = Vector2i.DOWN
				Room.Direction.EAST:
					vector_dir = Vector2i.RIGHT
				Room.Direction.WEST:
					vector_dir = Vector2i.LEFT

			var doors: Dictionary[Room.Direction, bool] = get_doors(pos)
			if (doors[Room.Direction[dir]]):
				room_by_coords[pos] \
					.neighbours[Room.Direction[dir]] \
						= room_by_coords[pos + vector_dir]
		room_by_coords[pos].setup()

func generate(seed: int = -99999):
	'''
	Generates seed if none specified
	'''
	if seed == -99999:
		rng.randomize()
		seed = rng.seed
	else:
		rng.seed = seed
		
	print("Using seed: ", seed)
	
	generate_layout()
	choose_rooms()
	generate_corridors()
	room_by_coords[Vector2i.ZERO].activate(true)

	print(":(")
	
	generation_done.emit()
